version: '3.1'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - rabbitmq_go_net
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  redis-master:
    image: 'bitnami/redis:latest'
    container_name: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_PASSWORD: ''
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/bitnami

  database:
    image: postgres:latest
    container_name: 'database'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres:
  redis:
  rabbitmq: