CREATE TABLE hotel (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255) NOT NULL,
    preco_noite DECIMAL(10, 2) NOT NULL,
    avaliacao_media DOUBLE PRECISION,
    numero_avaliacoes INTEGER
);

CREATE TABLE hotel_comodidades (
    hotel_id INT8 REFERENCES hotel(id) ON DELETE CASCADE,
    comodidade VARCHAR(255) NOT NULL,
    PRIMARY KEY (hotel_id, comodidade)
);

CREATE TABLE tipo_quarto (
     id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     descricao VARCHAR(50) NOT NULL
);

CREATE TABLE quarto (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id INT8 REFERENCES hotel(id) ON DELETE CASCADE,
    tipo_id INT8 REFERENCES tipo_quarto(id) ON DELETE SET NULL,
    numero VARCHAR(50) NOT NULL,
    preco_noite DECIMAL(10, 2) NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE status_reserva (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL
);

CREATE TABLE reserva (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id INT8 REFERENCES hotel(id) ON DELETE CASCADE,
    quarto_id INT8 REFERENCES quarto(id) ON DELETE CASCADE,
    status_id INT8 REFERENCES status_reserva(id) ON DELETE SET NULL,
    data_checkin DATE NOT NULL,
    data_checkout DATE NOT NULL,
    nome_cliente VARCHAR(255) NOT NULL,
    contato_cliente VARCHAR(255) NOT NULL,
    detalhes_pagamento TEXT
);

CREATE TABLE tipo_notificacao (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL
);

CREATE TABLE status_notificacao (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL
);

CREATE TABLE notificacao (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id INT8 REFERENCES reserva(id) ON DELETE CASCADE,
    tipo_id INT8 REFERENCES tipo_notificacao(id) ON DELETE SET NULL,
    status_id INT8 REFERENCES status_notificacao(id) ON DELETE SET NULL,
    data_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
